#!/bin/bash

# This program merges two mieterlisten (one from karthago and one from dw)







# check to add kreditor with number first than the name
# s=$0
# base="${s##*/}"
# [ $# -lt 2 ] && { echo "Usage: $base kreditornummer;\"Firmename\""; exit 1; }

# start of script
dw_download='ftp://ftp.docuware-online.de/QkmuGpfC_GG9qAH_dkHVSWav2SVM5SWFQl5GGyCY0/data/mieter_objekte.csv'
ftp -in $dw_download

ruby ~/Dotfiles/helpers/Mieter_DW_Update/add_mieter.rb mieter_objekte.csv "$1"

dw_server='ftp://ftp.docuware-online.de/QkmuGpfC_GG9qAH_dkHVSWav2SVM5SWFQl5GGyCY0/data/'
ftp -in -u $dw_server "mieter_objekte.csv"

rm mieter_objekte.csv
rm "$1"
